pipeline {
    agent any
    environment {
        DOCKER_FILE = "./ci/Dockerfile"
        HARBOR_ADDR = "your.harbor.addr"     // 示例，请替换为你实际使用的 Harbor 地址
        APP_NAME    = "simple-java-maven-docker-app"        // 示例，请根据实际情况填写
    }
    options {
        skipStagesAfterUnstable()
    }
    tools {
        maven 'maven3.9.10'  // 对应你之前配置的 Maven 名称
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Docker Build') {
            steps {
//                 sh 'docker build -t ${APP_NAME} ${DOCKER_FILE}'
                sh 'docker build -t ${APP_NAME} .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8081:8080 --name ${APP_NAME} ${APP_NAME}'
            }
        }
    }
}